NUM_GPUS: 8
MODEL:
  TYPE: 'mask_rcnn'
  PRECISION: 'float16'
  CLASSES: ['__background__',
            'person', 'bicycle', 'car', 'motorcycle', 'airplane',
            'bus', 'train', 'truck', 'boat', 'traffic light',
            'fire hydrant', 'stop sign', 'parking meter', 'bench',
            'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant',
            'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag',
            'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball',
            'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard',
            'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife',
            'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli',
            'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
            'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop',
            'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven',
            'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors',
            'teddy bear', 'hair drier', 'toothbrush']
BACKBONE:
  TYPE: 'resnet50_v1a.fpn'
  NORM: 'SyncBN'
  FREEZE_AT: 0
FPN:
  MIN_LEVEL: 2
  MAX_LEVEL: 6
  NORM: 'SyncBN'
ANCHOR_GENERATOR:
  STRIDES: [4, 8, 16, 32, 64]
RPN:
  NUM_CONV: 2
FAST_RCNN:
  NUM_CONV: 4
  NUM_FC: 1
  NORM: 'SyncBN'
MASK_RCNN:
  NORM: 'SyncBN'
SOLVER:
  BASE_LR: 0.1
  WEIGHT_DECAY: 0.00004
  DECAY_STEPS: [81944, 88773]
  MAX_STEPS: 92187
  SNAPSHOT_EVERY: 1250
  SNAPSHOT_PREFIX: 'coco_mask_rcnn_R_50_FPN_lsj'
TRAIN:
  WEIGHTS: '../data/pretrained/R-50-A_in1k_cls120e.pkl'
  DATASET: '../data/datasets/coco_train2017'
  LOADER: 'mask_train'
  IMS_PER_BATCH: 8
  SCALES: [1024]
  SCALES_RANGE: [0.1, 2.0]
  MAX_SIZE: 1024
  CROP_SIZE: 1024
TEST:
  DATASET: '../data/datasets/coco_val2017'
  JSON_DATASET: '../data/datasets/coco_instances_val2017.json'
  EVALUATOR: 'coco'
  IMS_PER_BATCH: 1
  SCALES: [800]
  MAX_SIZE: 1333
